Add the LICENSES directory for install and use the corrected name in …
dlr-gtlab/gtlab-core pull request #1091
Opened 2023-12-18 13:51 UTC by jensschmeink

…the about dailog

## Description

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

/label ~InProgress

2023-12-18 16:48 UTC, rainman110 requested changes
As much as I'd like to approve, I don't think that installing unconditionally to /LICENSES is a good idea.

This is a non-standard director, in particular on Linux. Assume, you install GTlab to /usr, then all GTlab licenses are installed to /usr/LICENSES. This is definitely not the right place. We already use non-standard directory layouts but we should not make it worse.

Instead, I propose to install to `share/gtlab/LICENSES` or a similar location.

2023-12-19 08:05 UTC, rainman110 commented
Oh no! Please don't differentiate between linux and windows. Also never install to a absolute location (/usr).

Just install to CMAKE_INSTALL_PREFIX/share/gtlab/licenses, i.e. 

```
install(DIRECTORY LICENSES/ share/gtlab/licenses)
```

You just have done so much work 😞 . I am sorry

2024-01-23 09:51 UTC, jensschmeink commented on src/app/dialogs/gt_aboutdialog.cpp
> +        gtError() << tr("Please contact the developers for further information.");
```suggestion
```

2024-01-25 16:29 UTC, rainman110 approved these changes
Nice work :)

2024-01-25 16:30 UTC, merged