Update gt_propertymodel.cpp
dlr-gtlab/gtlab-core pull request #1153
Opened 2024-03-27 08:23 UTC by jensschmeink

## Description

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-03-27 11:13 UTC, jensschmeink commented
This is a first solution for the problem. But as the tool tip might not be seen by the user a more convenient solution might be added in 2-1.
Currently the model view structure of 2-0-6 here would have to be manipulated for another solution (Maybe by a delegate ...)

2024-03-27 11:45 UTC, jensschmeink commented
@rainman110 Do you understand why the pipeline fails?

2024-03-27 13:22 UTC, rainman110 commented
> @rainman110 Do you understand why the pipeline fails?

Please rebase on current master.

2024-03-27 14:33 UTC, jensschmeink commented
@rainman110 please check for approval

2024-03-28 10:26 UTC, rainman110 requested changes

2024-03-28 10:26 UTC, rainman110 commented on src/gui/dock_widgets/properties/gt_propertymodel.cpp
> +        if (role == Qt::ToolTipRole)
Can you please change the code to avoid the deep nesting? There are many if statements nested, which makes the code hard to read. Use early returns, if possible.

2024-03-28 10:42 UTC, jensschmeink commented
@rainman110 i reduced the nested loops

2024-03-28 10:49 UTC, rainman110 approved these changes
Much better, thanks :)

2024-03-28 10:50 UTC, merged