Make tasks groups executable from console
dlr-gtlab/gtlab-core pull request #1179
Opened 2024-04-15 10:52 UTC by jensschmeink

If a task is organized in a task group which might not be the default group (normally the users group) the task cannot be executed in the console application.

This is fixed in this PR.
Call the run function now as following:
GTlabConsole run <PROJECT_ID> <TASK_ID> <TASK_GROUP_ID> (last one is optional)

## Description
If the given <TASK_GROUP_ID> is not empty the task group is switched to the given group and the task is searched and if found executed. 
For a cleanup of the batch the functions related to process execution are extracted to new files in a new namespace.

## How Has This Been Tested?
Manual tests of execution of a task which is part of another task group

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-04-15 13:25 UTC, jensschmeink commented
Most changed lines are the results of the switch from qDebug to gtLogging and the move of the process execution related functions to new files

2024-04-16 14:52 UTC, rainman110 requested changes
There seems to be some confusion regarding when to use gtError and gtWarning.

IMHO, an error should be logged, when the applications stops and returns a non-zero error code. Please check all occurences, I did not annotate all of the changed lines, as there are many of them.

Also, since gtError etc append [ERROR], you don't need to add it manually.

Finally, the function getTask could be changed, that it also works without a groupId. Then, you can simplify the calling code.

2024-04-16 14:52 UTC, rainman110 commented on src/batch/batch.cpp
> +        gtWarning() << QStringLiteral("ERROR: ")
If this is a warning, why do you add "Error"? I think you simply need to remove the first part of the error message.

 Imho, this needs to be an error, as the command is failing!

2024-04-16 14:52 UTC, rainman110 commented on src/batch/batch.cpp
> +        gtWarning() << QStringLiteral("ERROR: ")
same as above.  Imho, this needs to be an error, as the command is failing!

2024-04-16 14:52 UTC, rainman110 commented on src/batch/batch.cpp
> +        gtWarning() << QStringLiteral("ERROR: ")
same as above.  Imho, this needs to be an error, as the command is failing!

2024-04-16 14:52 UTC, rainman110 commented on src/batch/batch.cpp
> +        gtWarning() << QStringLiteral("ERROR: ")
same as above. Imho, this needs to be an error, as the command is failing!

2024-04-16 14:52 UTC, rainman110 commented on src/batch/gt_consolerunprocess.cpp
> +        gtWarning() << QObject::tr("Run method without arguments is invalid");
Why is this a warning?

2024-04-16 14:52 UTC, rainman110 commented on src/batch/gt_consolerunprocess.cpp
> +    }
Why don't you change getTask in a way. that it can handle an empty taskGroupId instead of needing here an if statement?

2024-04-16 14:52 UTC, rainman110 commented on src/batch/gt_consolerunprocess.cpp
> +gt::console::getTask(GtProject* project, const QString& groupid,
Please extend for the case, that the groupId could be empty, such that it will search in the default user folders.

2024-04-16 14:52 UTC, rainman110 commented on src/batch/gt_consolerunprocess.cpp
> +    {
This does not seem to make any sense. Either the variable `check` changes in between, then you need to reassign check to the result of line 363.

Otherwise you can implement everything in one `if(!check)` block.

2024-04-16 14:52 UTC, rainman110 commented on src/batch/gt_consolerunprocess.cpp
> +        gtError() << QStringLiteral("ERROR:")
Remove "ERROR: " string

2024-04-16 14:53 UTC, rainman110 commented
Please append the changelog!

2024-04-17 06:41 UTC, rainman110 approved these changes
Thank you, this looks better.

I am not sure, whether it is now actually better to use the logging here instead of plain cerr / cout, when the console application is reporting an error to the user.

But lets postpone this discussion in a separate issue.

The implementation itself is now fine. Thank you!

2024-04-17 06:42 UTC, merged