add basic changes to fix problem
dlr-gtlab/gtlab-core pull request #1214
Opened 2024-05-06 14:44 UTC by jensschmeink

## Description

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-05-13 08:30 UTC, rainman110 commented
@jensschmeink Please rebase to the current master to enable cppcheck

2024-05-13 09:09 UTC, rainman110 requested changes
The move elements function is now too long. Can you please subdivide it into smaller sub-functions. It is currently very hard to read and understand.

2024-05-13 09:59 UTC, jensschmeink commented
> The move elements function is now too long. Can you please subdivide it into smaller sub-functions. It is currently very hard to read and understand.

I divided parts of the function in seperate functions

2024-05-15 06:17 UTC, jensschmeink commented
@rainman110 after the warning is hidden now, can we merge?

2024-05-15 07:03 UTC, rainman110 requested changes
So after having functional tests, this is my review on the code.

Please just add docstrings to the new functions in the header, see comments.

2024-05-15 07:17 UTC, jensschmeink commented on src/app/dock_widgets/process/gt_processdock.h
> +    QList<GtObject*> findObjectsOfIdenticalParentByMapping(
I needed to add a const version of the basic funtion "mapToSource()" which I added now.

2024-05-15 12:33 UTC, rainman110 commented on src/app/dock_widgets/process/gt_processdock.h
> +     */
```suggestion
     * @brief Returns the objects from the model given their model index.
     *
     * The indices are sorted based on their row number for this.
     *
     * *Note*: A check is performed to make sure that all objects have
     * the same parent. If not the case, an empty list is returned.
     *
     * @param source - Model indices
     * @return list of objects which corresponds to the indices
     */
```

2024-05-15 12:34 UTC, rainman110 commented on src/app/dock_widgets/process/gt_processdock.h
> +    QList<GtObject*> findObjectsOfIdenticalParentByMapping(
```suggestion
    QList<GtObject*> findObjectsOfSameParent(
```

2024-05-15 12:36 UTC, rainman110 commented on src/app/dock_widgets/process/gt_processdock.h
> +     * After the move of the objects given by the finalyMovedObjects from
I still dont understand, what the function is doing. The sentence is very long. Please write @brief a short description and optionally add details, if necessary after a blank line.

2024-05-15 12:48 UTC, jensschmeink commented on src/app/dock_widgets/process/gt_processdock.h
> +     * After the move of the objects given by the finalyMovedObjects from
@rainman110 I added some more lines to describe the functino

2024-05-15 12:58 UTC, rainman110 approved these changes

2024-05-15 13:43 UTC, merged