Remove all connections at once by button
dlr-gtlab/gtlab-core pull request #1242
Opened 2024-06-13 12:29 UTC by jensschmeink

## Description

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-06-13 13:00 UTC, jensschmeink commented
This PR should be merged in 2.0.X as it does not affect any exported classes

2024-06-13 13:29 UTC, jensschmeink commented
Add better colors for dark mode  
![grafik](https://github.com/dlr-gtlab/gtlab-core/assets/148551711/ef4c2296-5a76-446c-8292-09eba16414f8)

This is ofcourse only a suggestion.

2024-06-14 11:00 UTC, mariusalexander commented
@jensschmeink I like the new colors! 

I am wondering however, whether we should make it also possible to only remove connections of a specific component? After all the connection editor can only be opened on the root task, correct? 

Say we have a deeply nested process chain and you only want to disconnect a specific calculator or subtask. Maybe you could all a context menu entry to each component to address this use case? However, I do not use the connection editor that often so maybe this use case does not apply.

2024-06-14 11:03 UTC, rainman110 commented
I also agree with @mariusalexander, that we probably need a more fine-grained control on the removal.

I also like the idea of a context menu entry, when you select an object to remove all connections to that objects (and its properties). By clicking on the root object, you basically remove all connections.

2024-06-14 11:04 UTC, mariusalexander commented on src/gui/gt_colors.h
> +GT_GUI_EXPORT QColor portBrush();
I assumed it would return a QBrush. I would prefer a name like simply `port()` or `portBackground()`

2024-06-14 11:04 UTC, mariusalexander commented on src/gui/gt_colors.h
> +GT_GUI_EXPORT QColor portHoverEnter();
Same here, I would suggest simply `portHover()` or `portHoverBackground()`

2024-06-14 11:06 UTC, jensschmeink commented
> @jensschmeink I like the new colors!
> 
> I am wondering however, whether we should make it also possible to only remove connections of a specific component? After all the connection editor can only be opened on the root task, correct?
> 
> Say we have a deeply nested process chain and you only want to disconnect a specific calculator or subtask. Maybe you could all a context menu entry to each component to address this use case? However, I do not use the connection editor that often so maybe this use case does not apply.

Yes, you are right. The editor is always opened only for the root task.
I like your idea with the context menu and will implement a first version

2024-06-14 11:07 UTC, mariusalexander commented
@jensschmeink What causes this black line in you screenshot?

![grafik](https://github.com/dlr-gtlab/gtlab-core/assets/52258575/7d43517b-51d6-47fe-9e70-388491ad2716)

2024-06-14 11:17 UTC, jensschmeink commented
> @jensschmeink What causes this black line in you screenshot?
> 
> ![grafik](https://private-user-images.githubusercontent.com/52258575/339744124-7d43517b-51d6-47fe-9e70-388491ad2716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjM1MjYsIm5iZiI6MTcxODM2MzIyNiwicGF0aCI6Ii81MjI1ODU3NS8zMzk3NDQxMjQtN2Q0MzUxN2ItNTFkNi00N2ZlLTllNzAtMzg4NDkxYWQyNzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDExMDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZWQ4ZWY1ZWI0NGQyZWYyNDkyZDgwNjk5NmIwNzNkMTNmYmRjMzI5ZTkzOGQyY2Y1MzdmNGZmMjY5MDZiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNg5LSiUIS74yg94FOLZ5ZtbB1tG_OO5RUjKPqXjFLA)

Good question. It seems to be a strange artifact of the connections. I have not changed anything about that. Is it also part of the existing implementation?

2024-06-14 11:48 UTC, mariusalexander commented
I don't see it in my editor

> > @jensschmeink What causes this black line in you screenshot?
> > ![grafik](https://private-user-images.githubusercontent.com/52258575/339744124-7d43517b-51d6-47fe-9e70-388491ad2716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjM1MjYsIm5iZiI6MTcxODM2MzIyNiwicGF0aCI6Ii81MjI1ODU3NS8zMzk3NDQxMjQtN2Q0MzUxN2ItNTFkNi00N2ZlLTllNzAtMzg4NDkxYWQyNzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDExMDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZWQ4ZWY1ZWI0NGQyZWYyNDkyZDgwNjk5NmIwNzNkMTNmYmRjMzI5ZTkzOGQyY2Y1MzdmNGZmMjY5MDZiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNg5LSiUIS74yg94FOLZ5ZtbB1tG_OO5RUjKPqXjFLA)
> 
> Good question. It seems to be a strange artifact of the connections. I have not changed anything about that. Is it also part of the existing implementation?

I do not see it in my editor

2024-06-17 06:29 UTC, jensschmeink commented
![grafik](https://github.com/dlr-gtlab/gtlab-core/assets/148551711/3efaa936-f211-40bc-b1ff-43529b4d31fb)  

The new version has the button to remove all connections but you can also right cklick any process element to remove all connections of this process element. But it is seperated for input and output. So if you use the disconnect on the left (input) side all input nodes of this process element (and all of its children) are removed but not there connections on the output side. This behaviour was the result of a talk of @mariusalexander and @jensschmeink

2024-08-19 12:44 UTC, rainman110 commented
@jensschmeink What is the status of this PR?

2024-08-19 12:46 UTC, jensschmeink commented
> @jensschmeink What is the status of this PR?

It is done but needs a final review

2024-08-20 07:40 UTC, rainman110 commented on src/gui/gt_colors.cpp
> +    return Qt::red;
Why do you check for dark mode? Also, this function will crash, if gtApp is a nullptr, i.e. in unit tests.

2024-08-20 07:52 UTC, jensschmeink commented on src/gui/gt_colors.cpp
> +    return Qt::red;
There was the plan to adapt the color depending on the test of the members of the GTlab Core meeting.

2024-08-21 07:40 UTC, jensschmeink commented on src/gui/gt_colors.cpp
> +    return Qt::red;
Not right now so it should be ready for a review

2024-08-21 12:13 UTC, rainman110 requested changes

2024-08-21 12:13 UTC, rainman110 commented on src/app/mdi_items/process_env/entities/gt_processpropertyconnectionentity.cpp
> +    if (m_connection)
Please use early return as in the  method below to improve readability.

2024-08-21 12:13 UTC, rainman110 commented on src/app/mdi_items/process_env/entities/gt_processpropertyconnectionentity.h
> +    bool connectedToProcessComponent(QString const& uuid, bool inPort);
This should be const, shouldn't it?

2024-08-21 12:13 UTC, rainman110 commented on src/app/mdi_items/process_env/gt_processconnectiongraphicsview.cpp
> +        if (auto e = dynamic_cast<GtProcessPropertyConnectionEntity*>(i))
Could you replace this with qobject_cast, since this should have better performance.

You could also use early continue here, if i is not an entity. Also rename i -> item, otherwise it looks like a counter.

2024-08-21 12:13 UTC, rainman110 commented on src/app/mdi_items/process_env/gt_processconnectiongraphicsview.cpp
> +            for (auto const& u : allUuids)
Use std::find_if

2024-08-21 12:13 UTC, rainman110 commented on src/app/dock_widgets/process/gt_processconnectioneditor.cpp
> +    m_connectionView->removeAllConnections(m_connectionView->root()->uuid());
What happens, if you don't have a root object? Can this happen?

2024-08-21 12:13 UTC, rainman110 commented on src/app/mdi_items/process_env/entities/gt_processconnectionview.cpp
> +    GtProcessConnectionItem* i = connModel->itemFromIndex(index);
rename to item

2024-08-21 12:13 UTC, rainman110 commented on src/app/mdi_items/process_env/entities/gt_processconnectionview.cpp
> +    if (i->itemType() != GtProcessConnectionItem::PROCESS_COMPONENT) return;
```suggestion
    if (!i || i->itemType() != GtProcessConnectionItem::PROCESS_COMPONENT) return;
```

2024-08-26 13:51 UTC, jensschmeink commented on src/app/mdi_items/process_env/gt_processconnectiongraphicsview.cpp
> +        if (auto e = dynamic_cast<GtProcessPropertyConnectionEntity*>(i))
The class QGraphicsItem is not a qObject and therefore the qobject_cast is not working here

2024-08-26 14:00 UTC, rainman110 commented on src/app/mdi_items/process_env/gt_processconnectiongraphicsview.cpp
> +        if (auto e = dynamic_cast<GtProcessPropertyConnectionEntity*>(i))
Ok, makes sense

2024-08-27 12:56 UTC, merged

2024-08-27 13:01 UTC, rainman110 commented
Damn, we forgot the changelog. I'll add an entry.