fix.: add task as dummy object to taskgroup if the task-module did no…
dlr-gtlab/gtlab-core pull request #1286
Opened 2024-09-10 12:14 UTC by NitenIchiry

…t load

GtTasks recognized as dummy are now added to the datamodel.

In `GtTaskGroup` 

## Description

In `GtTaskGroup` task-objects read from momento are now additionaly checked if they are dummy objects and then added to the datamodel as background objects with the recognizable red color of dummy objects.

Previously a wrong error message was printed that the task file is invalid. This happened because the GtDummy-object could not be parsed to GtTask.

https://github.com/dlr-gtlab/gtlab-core/issues/612

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-09-10 12:18 UTC, NitenIchiry commented
@rainman110 I was not entirely sure how to implement this change. A different idea of me was to add a new function which checks the task-items for dummy objects prior to the `createTaskFromFile` function.

Let me know what you would prefer in this case. The error is fixed in this case. But there is still an error scenario when the GtObject returned by createTaskFromFile returns a nullpointer. Also the name of the function should be changed with the current solution.

2024-09-10 13:35 UTC, rainman110 requested changes
In principle looks good, but please keep the unique_ptr api.

In line 135, you could use the function `gt::unique_object_cast`, i.e.

auto taskObject = gt::unique_qobject_cast<GtTask>(std::move(newTask));

2024-09-10 13:36 UTC, rainman110 commented
> @rainman110 I was not entirely sure how to implement this change. A different idea of me was to add a new function which checks the task-items for dummy objects prior to the `createTaskFromFile` function.

I think, the general implementation is fine, i.e. adding a dummy object to the process tree.

2024-09-19 08:04 UTC, NitenIchiry commented
> In principle looks good, but please keep the unique_ptr api.
> 
> In line 135, you could use the function `gt::unique_object_cast`, i.e.
> 
> auto taskObject = gt::unique_qobject_cast(std::move(newTask));

I cannot get the unique object cast to work as it was described here. Do you have a typo anywhere?

2024-10-10 07:59 UTC, NitenIchiry commented on src/core/process_management/gt_taskgroup.cpp
> +GtObject*
I reimplemented the unique pointer. Let me know what you think.

2024-10-10 07:59 UTC, NitenIchiry commented on src/core/process_management/gt_taskgroup.cpp
> +            auto retval = qobject_cast<GtTask*>(newTask);
Changed the name

2024-10-10 08:00 UTC, NitenIchiry commented on src/core/process_management/gt_taskgroup.cpp
> +                newTask->deleteLater();
Well unique_objects cannot be deleted with delete, but with deleteLater (ownership is transfered). I changed it back to delete and release the object now. Let me know what you think.

2024-10-10 08:01 UTC, NitenIchiry commented
It is ready for a final assessment.

2024-10-14 11:22 UTC, rainman110 requested changes

2024-10-14 11:22 UTC, rainman110 commented on src/core/process_management/gt_taskgroup.cpp
> +
This should do much less imho

1) The manual delete should not be necessary
2) Why do you treat dummy objects similar than other objects

So here,'s what I'd do

for each task
 - newTask = createFromFile...
 - if (!newTask) continue;
 - if (task->isDummy) printWarning;
 - else assert (task type is GtTask)
 - appendChild(newTask.release)

No need for ownership transfer etc.

2024-10-14 11:22 UTC, rainman110 commented on src/core/process_management/gt_taskgroup.cpp
> +
Theoretically, the memento restore should already warn, that a dummy task was created, so the warning could be probably also removed

2024-10-17 09:07 UTC, NitenIchiry commented on src/core/process_management/gt_taskgroup.cpp
> +
`WARN  [11:03:11] Creating dummy object for unknown class 'GtpyTask'.
DEBUG [11:03:11] [Core] dummy task created ({dde42211-6bfa-4136-87c6-c7f2a56be5ea})
DEBUG [11:03:11] [Core] new task created ({8d9b8f01-b92f-409e-97e9-84be68878d9a})`

Currently A Warning and Debug message is printed. Should I remove the dummy task created message ?

2024-10-17 09:08 UTC, NitenIchiry commented on src/core/process_management/gt_taskgroup.cpp
> +
I added an assert. Was it your idea to add it like this, or did you have a different idea ?

2024-10-17 09:10 UTC, NitenIchiry commented
![Screenshot 2024-10-17 110328](https://github.com/user-attachments/assets/d33655a8-1764-452a-82cf-9c3c50b698e7)
You cannot press the button to execute tasks which contain dummy bjects atm. We should add a new issue for this in which we add a new type of task a `GtDummyTask` or something similar. That was what we discussed, wasnt it ?

2024-10-17 09:13 UTC, rainman110 commented
> You cannot press the button to execute tasks which contain dummy bjects atm. We should add a new issue for this in which we add a new type of task a `GtDummyTask` or something similar. That was what we discussed, wasnt it ?

I think this is a good default behaviour for now. Nothing to do on your side. What we need to implement is to make it skippable (in a separate issue)

2024-10-17 10:42 UTC, NitenIchiry commented
I removed the unneeded check for GtObjects in the `createTaskFromFile` function

2024-10-17 10:58 UTC, rainman110 commented on src/core/process_management/gt_taskgroup.cpp
> +    GtObject* retval = nullptr;
As far as i can see, retval is not used anymore.

2024-10-17 10:59 UTC, rainman110 commented on src/core/process_management/gt_taskgroup.cpp
> +            assert(gtTask != nullptr && "newTask must be of type GtTask.");
```suggestion
            assert(qobject_cast<GtTask*>(newTask.get()) && "newTask must be of type GtTask.");
```

This way, the cast is only performed in debug mode.

2024-10-17 12:59 UTC, NitenIchiry commented
Thank you for the fast review. It should be fine now.

2024-10-17 13:04 UTC, rainman110 commented
One more small thing, sorry i should have addressed this earlier: Please add a line to the changelog, that dummy tasks are now displayed in the process explorer 

(we only add to the changelog, if something user-visible has changed).

Also please remove the draft status from the PR.

2024-10-21 10:32 UTC, rainman110 approved these changes

2024-10-21 10:33 UTC, merged