Operators for double int and string propeties
dlr-gtlab/gtlab-core pull request #1290
Opened 2024-09-11 13:28 UTC by jensschmeink

Basic implementation of some operators for +=, -=, ... 
These are now implemented for double, int and string property

## Description

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-09-11 13:29 UTC, jensschmeink commented
Basic unittests are needed but currently missing

2024-09-12 08:44 UTC, jensschmeink commented on src/dataprocessor/property/gt_doubleproperty.cpp
> +    assert(a != 0.0);
```suggestion
    assert(b != 0.0);
```

2024-09-26 14:44 UTC, jensschmeink commented on src/dataprocessor/property/gt_doubleproperty.h
> +    inline void operator/=(double const& b);
```suggestion
    void operator+=(double const& b);
    void operator-=(double const& b);
    void operator*=(double const& b);
    void operator/=(double const& b);
```

2024-09-26 14:44 UTC, jensschmeink commented on src/dataprocessor/property/gt_intproperty.h
> +    inline void operator/=(int b);
```suggestion
    void operator+=(int b);
    void operator-=(int b);
    void operator*=(int b);
    void operator/=(int b);
```

2024-09-26 14:45 UTC, jensschmeink commented on src/dataprocessor/property/gt_stringproperty.h
> +    inline void operator+=(const QString& b);
```suggestion
    void operator+=(const QString& b);
```

2024-09-26 14:56 UTC, rainman110 requested changes
Looks good, but could you fixup the indentation error in the tests?

2024-09-27 06:13 UTC, jensschmeink commented on tests/unittests/datamodel/test_gt_doubleproperty.cpp
> +    ASSERT_DOUBLE_EQ(prop.get(), 3.3 / div);
```suggestion
    GtDoubleProperty prop("prop", "test", "test", GtUnit::Category::None, 4.0);
	
    // operator+=
    double sum = 4.4;
    prop.setVal(3.3);
	
    prop += sum;
    ASSERT_DOUBLE_EQ(prop.get(), 3.3 + sum);
	
    // operator-=
    double diff = 4.4;
    prop.setVal(3.3);
	
    prop -= diff;
    ASSERT_DOUBLE_EQ(prop.get(), 3.3 - diff);
	
    // operator*=
    double factor = 4.4;
    prop.setVal(3.3);
	
     prop *= factor;
    ASSERT_DOUBLE_EQ(prop.get(), 3.3 * factor);
	
    // operator/=
    double div = 4.4;
    prop.setVal(3.3);
	
    prop /= div;
    ASSERT_DOUBLE_EQ(prop.get(), 3.3 / div);
```

2024-09-27 06:14 UTC, jensschmeink commented on tests/unittests/datamodel/test_gt_intproperty.cpp
> +    EXPECT_EQ(prop.get(), 3);
```suggestion
    GtIntProperty prop("prop", "test", "test", 4);
    // operator+=
    int sum = 4;
    prop.setVal(13);
	
    prop += sum;
    EXPECT_EQ(prop.get(), 13 + sum);

    // operator-=
    int diff = 4;
    prop.setVal(13);
	
    prop -= diff;
    EXPECT_EQ(prop.get(), 13 - diff);
	
    // operator*=
    int factor = 4;
    prop.setVal(13);
	
    prop *= factor;
    EXPECT_EQ(prop.get(), 13 * factor);
	
    // operator/=
    int div = 4;
    prop.setVal(13);
	
    prop /= div;
    EXPECT_EQ(prop.get(), 3);
```

2024-09-27 06:14 UTC, jensschmeink commented on tests/unittests/datamodel/test_gt_stringproperty.cpp
> +    ASSERT_STREQ(prop.get().toStdString().c_str(), "GTlab is nice!");
```suggestion
    GtStringProperty prop("prop", "test", "test", "hello");
	
    // operator+=
    QString added = " is nice!";
    prop.setVal("GTlab");
	
    prop += added;
    ASSERT_STREQ(prop.get().toStdString().c_str(), "GTlab is nice!");
```

2024-09-27 06:15 UTC, jensschmeink commented
> Looks good, but could you fixup the indentation error in the tests?

Done

2024-09-27 07:41 UTC, rainman110 commented on tests/unittests/datamodel/test_gt_doubleproperty.cpp
> +     prop *= factor;
I don't want to be picky, but there's still a indentation error ;)

2024-09-27 07:43 UTC, jensschmeink commented on tests/unittests/datamodel/test_gt_doubleproperty.cpp
> +     prop *= factor;
```suggestion
    prop *= factor;
```

2024-10-01 11:01 UTC, rainman110 approved these changes

2024-10-01 11:02 UTC, rainman110 commented
@jensschmeink Please stash before merge

2024-10-01 11:08 UTC, merged