feat.: Adding Update Project Procedure to Batch-Mode
dlr-gtlab/gtlab-core pull request #1308
Opened 2024-10-10 13:23 UTC by NitenIchiry

## Description

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-10-10 13:29 UTC, NitenIchiry commented
@rainman110 My Initial Idea was to have a default mode which either takes 2 or 3 arguments. One for the ProjectName, One for the new duplicate Project Path and One optionally IF you want to rename the project. Then I have an overwrite option, which only takes the project name and then upgrades it. Tell me if you are okay with this general idea. 

Then I was not sure about including my newly written functions into the `batch.cpp`. Should I create a new namespace/class for upgrade routines ? So far this works by either:

- `.\GTlabConsole.exe --dev upgrade_Project -o "New Project"`
- `.\GTlabConsole.exe --dev upgrade_Project  "New Project" "newpath" [optionally "newName"]`

Maybe we can open a discussion here. I am not very used to writing bash commands. Maybe you could give me some useful insights, if I am doing anything wrong.

2024-10-10 13:45 UTC, rainman110 commented
@NitenIchiry I would change the call a little bit:

.\GTlabConsole.exe  upgrade_project <project_path> [-o <new_project_path>]

For example
 - .\GTlabConsole.exe  upgrade_project c:\data\my_project
 - .\GTlabConsole.exe  upgrade_project c:\data\my_project -o c:\data\my_new_project
 
 The command "upgrade_project" uses lower case letters and the -o (Output Path) is optional.

2024-10-10 13:47 UTC, rainman110 commented
@NitenIchiry Regarding the code layout, you don't need a new namespace, but add the code to a new file (gt_upgradeproject.h/.cpp).

2024-10-11 06:37 UTC, rainman110 commented
@NitenIchiry Are you still working on it, or should the code be reviewed? If you are working on it, switch the PR to draft

2024-10-14 09:07 UTC, rainman110 requested changes
Generally look good, but please adapt the command line interface as suggested by me in the comments.

2024-10-14 09:07 UTC, rainman110 commented on src/batch/gt_consoleupgradeproject.h
> +#ifndef GT_CONSOLEUPGRADEPROJECT_H
Please add the file headers, in particular containing license and copyright. See other headers.

2024-10-14 09:07 UTC, rainman110 commented on src/batch/gt_consoleupgradeproject.cpp
> +#include "gt_consoleupgradeproject.h"
Please add the file headers, in particular containing license and copyright. See other headers.

2024-10-14 09:07 UTC, rainman110 commented on src/batch/gt_consoleupgradeproject.cpp
> +    if (project->upgradesAvailable())
Please use early return to avoid nesting, i.e.

```cpp
if (!project->upgradesAvailable())
{
    gtDebug() << "Project is up to date no further upgrades needed at the moment.";
    return 0;
}
```

2024-10-14 09:07 UTC, rainman110 commented on src/batch/batch.cpp
> +    initPosArgument("upgrade_Project", gt::console::upgrade_Project,
Please change the command name to "upgrade_project".

2024-10-14 09:07 UTC, rainman110 commented on src/batch/gt_consolerunprocess.cpp
> +    runOptions.append(GtCommandLineOption{
Please don't use "-o" as overwrite, but as output path as suggested in my previous comment. hence, you need to change the logic here a bit.

2024-10-14 09:07 UTC, rainman110 commented on src/batch/gt_consoleupgradeproject.cpp
> +gt::console::upgrade_Project(const QStringList &args)
please change to `upgradeProject` to match the code style.

2024-10-14 10:50 UTC, NitenIchiry commented on src/batch/gt_consoleupgradeproject.cpp
> +#include "gt_consoleupgradeproject.h"
Done

2024-10-14 11:47 UTC, rainman110 commented on src/batch/gt_consoleupgradeproject.cpp
> +    }
This code is more or less a copy of the code the gt_projectui. This is a problem, since when we change the implemenation  of one, we must remember to change it here as well.

So please refactor the code to provide only one implementation , e.g. in gtproject. Please make sure, that you add the possibilty to run certain things in a separate thread, as the gt_projectui does (e.g. by checking batch mode or not)

2024-10-15 14:34 UTC, NitenIchiry commented on src/batch/batch.cpp
> +    initPosArgument("upgrade_project", gt::console::upgrade_project,
I added a new help function now. Sorry for the sloppy work.

2024-10-17 11:33 UTC, rainman110 commented on src/core/gt_project.cpp
> +        }
```suggestion
        // upgrade project data in separate thread if possible
        gtApp->loadingProcedure(gt::makeLoadingHelper([&project]() {
            project->createBackup();
            project->upgradeProjectData();
        }).get());
```

2024-10-17 11:35 UTC, rainman110 commented on src/core/gt_project.cpp
> +        }
Same here

```suggestion
        gtApp->loadingProcedure(gt::makeLoadingHelper([&newProject]() {
            newProject->upgradeProjectData();
        }).get());
```

2024-10-17 11:36 UTC, rainman110 commented on src/core/gt_project.h
> +    bool upgradeProjectRoutine(bool overwriteExistingData, const QString &newProjectFilePath);
Imho, we don't need overwriteExistingData variable! If newProjectFilePath is empty or the old path, we overwrite.

2024-10-17 13:12 UTC, NitenIchiry commented on src/core/gt_project.h
> +    bool upgradeProjectRoutine(bool overwriteExistingData, const QString &newProjectFilePath);
I changed the parameters and applied your suggestions.

2024-10-21 15:39 UTC, rainman110 commented
@NitenIchiry I am taking over now. Please don't commit in here anymore. I'll also rebase this on 2.0.X

2024-10-21 16:16 UTC, rainman110 commented
@NitenIchiry I found a couple of bugs, that I have fixed:

1. In the gui, a new project was created even though it was set up to overwrite the current project.
2. In batch mode, the project upgrade did not work, since it was not imported to any session. I fixed that, by creating a temporary session.
3. A wrong help text to the upgrade command was printed (it was still using the help from the "run" command)

I rebased the code to the branch 2.0.x. So if you plan to do anything in this branch, please reset your local branch to this one (don't just pull, otherwise you'll get strange merges)

2024-10-22 08:26 UTC, rainman110 approved these changes

2024-10-24 12:01 UTC, merged