Replace QValidator by RegExpPattern-String
dlr-gtlab/gtlab-core pull request #1317
Opened 2024-10-25 06:44 UTC by jensschmeink

## Description

## How Has This Been Tested?

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-10-25 07:39 UTC, jensschmeink commented
@rainman110 This is a first base for a discussion. This was the simplest approach to remove the GUI dependency.
What do you think about this?

2024-10-25 07:42 UTC, jensschmeink commented on src/gui/dock_widgets/properties/items/gt_propertyitem.cpp
> +                                                 lineEdit);
```suggestion
                if (!s->validator().isEmpty()) 
                    validator = new QRegExpValidator(QRegExp(s->validator()), lineEdit);
```

2024-10-25 09:53 UTC, rainman110 commented on src/dataprocessor/property/gt_stringproperty.h
> +            "[A-Za-z0-9\\_\\-\\+\\^\\°\\/\\*\\.\\,\\(\\)\\[\\]]*");
Minor: Please comment, what this regex is. Ideally, use a named regex from gt_regexp.h

Major: Do you know, how often this is used in the modules? We already have API changes due to the qkeysequence change, requiring source modifications of a module. This would be another breaking API change. I though need to think about, how we can maintain API compatibility, but still without requiring QValidator in the dataprocessor.

2024-10-25 10:20 UTC, jensschmeink commented on src/dataprocessor/property/gt_stringproperty.h
> +            "[A-Za-z0-9\\_\\-\\+\\^\\°\\/\\*\\.\\,\\(\\)\\[\\]]*");
In the master build I had to do 3 or 4 adaptions in the modules from TWK (Performance, IntelliGraph & Geometry).

I used now the regexp namespace to cleanup the usage

2024-11-04 11:50 UTC, jensschmeink commented
@rainman110 I applied your suggestion to use the QRegularExpression class for a clearer and modern interface. Please check again, if this is ok

2024-11-04 12:19 UTC, rainman110 requested changes
I just have a small suggestion for the docstring,

2024-11-04 12:19 UTC, rainman110 commented on src/dataprocessor/property/gt_stringproperty.h
> +     * vale manipulation. The default value is the GTRegExp "forExpressions"
```suggestion
     * @param validationPattern - this regular expression can be set to validate the
     * manipulation of the value. The default value is the GTRegExp "forExpressions"
```

2024-11-04 14:03 UTC, jensschmeink commented
> I just have a small suggestion for the docstring,

done

2024-11-04 14:17 UTC, rainman110 approved these changes

2024-11-04 14:18 UTC, merged