Add color property
dlr-gtlab/gtlab-core pull request #1330
Opened 2024-12-06 09:32 UTC by jensschmeink

## Description
The color property from geometry module were moved to core and extended with a dialog to select color instead of hexacode.
The property was not added as the others in core in the data model library as it is important not to use QColor there for the QtGui dependency.
Instead is is registered in the GtApplication 

## How Has This Been Tested?
I replaced the geometry version in the shape color node and it worked fine.

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

2024-12-06 09:39 UTC, jensschmeink commented
The implementation is just an idea. Fell free to modify

2024-12-09 10:04 UTC, rainman110 commented
@jensschmeink I fear, that providing a core property only for gui cases is the wrong approach. This leads to the same sitation that we are currently facing, namely that we cannot use QColor, because its defined in the Qt Gui Library. What happens, if some workflow that contains a color property is used in batch mode? 

Instead, we need to provide the color prorperty in out core library. To do so, we need to get rid of QColor, which is not a problem though. We could provide getters and setters for the RGB values such that there is no direct need for QColor. In the GUI library, we can provide a converter from ColorProperty to QColor.

2024-12-09 10:16 UTC, jensschmeink commented
> @jensschmeink I fear, that providing a core property only for gui cases is the wrong approach. This leads to the same sitation that we are currently facing, namely that we cannot use QColor, because its defined in the Qt Gui Library. What happens, if some workflow that contains a color property is used in batch mode?
> 
> Instead, we need to provide the color property in our core library. To do so, we need to get rid of QColor, which is not a problem though. We could provide getters and setters for the RGB values such that there is no direct need for QColor. In the GUI library, we can provide a converter from ColorProperty to QColor.

@rainman110 my current implementation does not affect out problem with QtGUI as it is not implemented in the core but in the GUI-library of GTlab. Of course I think it woule be possible to store the property in core using the RGB code. I see the advantage to register all core properties at the same place but with this implementation the property implementation is cleaner using QColor directly.

2024-12-09 10:21 UTC, jensschmeink commented
> @jensschmeink I fear, that providing a core property only for gui cases is the wrong approach. This leads to the same sitation that we are currently facing, namely that we cannot use QColor, because its defined in the Qt Gui Library. What happens, if some workflow that contains a color property is used in batch mode?
> 
> Instead, we need to provide the color property in our core library. To do so, we need to get rid of QColor, which is not a problem though. We could provide getters and setters for the RGB values such that there is no direct need for QColor. In the GUI library, we can provide a converter from ColorProperty to QColor.

@rainman110 I understand your point. I'll implement a new solution

2024-12-11 15:40 UTC, jensschmeink commented
@rainman110 There is already a conversion option of string and colors. Therefore I now implemented a solution based on the hex representation string of the colors. It worked as well and now is independent of GUI and now part of the core. We could add some converters maybe in the gt_color class.

2024-12-12 13:39 UTC, jensschmeink commented
@rainman110 I think now I have a version for a first review. Please have a look and give hints, advice and critics as needed.

2024-12-17 14:32 UTC, jensschmeink commented
New feature request: Usage of alpha value for transperancy

2024-12-20 09:53 UTC, rainman110 requested changes
Thanks for the PR.

In general, the code looks good. The most critical change is to correct the string conversion of colors with alpha. The alpha value needs to be at the end of the string, not at the beginning (this is how is it used by all standards).

I'd like to test the usability from GTlab. Therefore, please also add a color property to the test module.

2024-12-20 09:53 UTC, rainman110 commented on src/gui/dock_widgets/properties/items/gt_colorpropertyitem.h
> +class GtColorPropertyItem : public GtPropertyItem
I'd like to test the color property in GTlab, could you please add the property to the test module?

2024-12-20 09:53 UTC, rainman110 commented on src/dataprocessor/property/gt_colorproperty.cpp
> +gt::rgb::valid() const
you don't need the function, if you switch to uint_8

2024-12-20 09:53 UTC, rainman110 commented on src/dataprocessor/property/gt_colorproperty.cpp
> +       << std::setw(2) << std::setfill('0') << std::hex << m_alpha
Please add alpha to the end, and only, if alpha != 255.

2024-12-20 09:53 UTC, rainman110 commented on src/gui/gt_application.cpp
> +    /// register gui related properties
This looks wrong to me. The color prop is not gui only! Where are the other properties registered?

2024-12-20 09:53 UTC, rainman110 commented on tests/unittests/datamodel/test_gt_colorproperty.cpp
> +TEST_F(TestGtColorProperty, initialization)
Please replace all ASSERT_* by EXPECT_* (use assert only, if you cannot continue the test, if the statement fails)

2024-12-20 10:00 UTC, jensschmeink commented on src/dataprocessor/property/gt_colorproperty.h
> +                    int r, int g, int b, int alpha = 255);
I used the value -1 to make the rgb object invalid. What would be a nice version to do this with the uint8_t arguments?

2024-12-20 10:02 UTC, jensschmeink commented
> Thanks for the PR.
> 
> In general, the code looks good. The most critical change is to correct the string conversion of colors with alpha. The alpha value needs to be at the end of the string, not at the beginning (this is how is it used by all standards).
> 
> I'd like to test the usability from GTlab. Therefore, please also add a color property to the test module.

For the hex code of the color with alpha I used the def

> Thanks for the PR.
> 
> In general, the code looks good. The most critical change is to correct the string conversion of colors with alpha. The alpha value needs to be at the end of the string, not at the beginning (this is how is it used by all standards).
> 
> I'd like to test the usability from GTlab. Therefore, please also add a color property to the test module.

The hex code with alpha in the beginning is based on the version as it is used in Qt. Shall I introduce a kind of wrapper for the QColor <-> QString conversion?

2024-12-20 10:07 UTC, jensschmeink commented on src/gui/gt_application.cpp
> +    /// register gui related properties
This is a relic of my old implementation. I'll fix this

2024-12-20 14:25 UTC, jensschmeink commented
@rainman110 I used your suggestions from the review and also made the line edit for the color definition not "read only" anymore. I added an interface to use the color-namespace for initialization to the interface. 
I hope now the property is ready for another review.

2024-12-20 14:26 UTC, jensschmeink commented
bad luck. I had no look at the unittests and need some minutes to fix them

2025-01-06 09:23 UTC, jensschmeink commented on src/dataprocessor/property/gt_colorproperty.cpp
> +    int newIntA = 255;
I found some strange behavior if the hex code is written directly to the uint8_t variables. The solution here is to use integer to fix the conversion as the std::hex works fine to write the int values and from there to the uint8 variables.

2025-01-06 09:24 UTC, jensschmeink commented on src/dataprocessor/property/gt_colorproperty.cpp
> +        shift = 2;
As we discussed the standard to write alpha in the end is more html and browser related style while alpha in the beginning is e.g. also used in QColor.

2025-01-27 07:30 UTC, jensschmeink commented
@rainman110 Please review this PR so it might be merged soon.

2025-01-27 13:28 UTC, merged